Add RedisAI

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -189,6 +189,46 @@ services:
       timeout: 10s
       retries: 120
 
+  redisai:
+    image: redislabs/redisai:1.2.6-cpu-bionic
+    healthcheck:
+      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
+      interval: 10s
+      timeout: 10s
+      retries: 120
+
+  setup-redis:
+    build:
+      context: .
+      target: "redis-setup"
+    depends_on:
+      redisai:
+        condition: service_healthy
+    command: >
+      bash -c '
+        /usr/local/bin/modelstore;
+        if [ $? -ne 0 ]; then
+          echo "Storing model into RedisAI failed!";
+          exit 1;
+        fi;
+        echo 'OK' > /usr/local/alldone;
+        echo "All done!";
+      '
+    volumes:
+      - type: bind
+        source: ${MODEL_PATH}
+        target: /var/local/model
+        read_only: true
+    environment:
+      - MODEL_PATH=/var/local/model
+      - REDIS_HOST=redisai
+      - REDIS_PORT=6379
+    healthcheck:
+      test: ["CMD-SHELL", "[ -f /usr/local/alldone ]"]
+      interval: 10s
+      timeout: 30s
+      retries: 120
+
   api:
     depends_on:
       es01:
@@ -196,6 +236,10 @@ services:
       es02:
         condition: service_healthy
       es03:
+        condition: service_healthy
+      redisai:
+        condition: service_healthy
+      setup-redis:
         condition: service_healthy
     image: "eiffel/geoss-search-service:${VERSION}"
     build:
@@ -233,6 +277,8 @@ services:
       - INIT_DATA=/var/local/metadata/data/
       - INIT_DATA_SCHEMA=/var/local/metadata/schema.yml
       - API_KEY=${API_KEY}
+      - REDIS_HOST=redisai
+      - REDIS_PORT=6379
 
 volumes:
   certs:
